[package]
name = "tty"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

[[bin]]
name = "tty"
test = false

[lib]
test = false

[features]
test_on_qemu = []

[dependencies]
os_units = "0.4.2"
rlibc = "1.0.0"
syscalls = { path = "../../libs/syscalls" }
