[workspace]
members = [
    "bootx64",
    "kernel",
    "libs/acpi",
    "libs/apic",
    "libs/boot_info",
    "libs/debug",
    "libs/frame_allocator",
    "libs/kernel_mem",
    "libs/predefined_mmap",
    "libs/qemu",
    "libs/r_acpi",
    "libs/uefi",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
