[workspace]
members = [
    "bootx64",
    "kernel",
    "libs/acpi",
    "libs/apic",
    "libs/boot_info",
    "libs/debug",
    "libs/frame_allocator",
    "libs/pic",
    "libs/predefined_mmap",
    "libs/qemu",
    "libs/r_acpi",
    "libs/uefi",
    "libs/vm",
    "servers/vm_server",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
