[workspace]
members = [
    "bootx64",
    "kernel",
    "libs/boot_info",
    "libs/debug",
    "libs/frame_allocator",
    "libs/kernel_mmap",
    "libs/page_range",
    "libs/qemu",
    "libs/uefi_wrapper",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
