[workspace]
members = [
    "bootloader/bootx64",
    "bootloader/uefi_wrapper",
    "libs/debug",
    "servers/init",
    "kernel",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
