[workspace]
members = [
    "bootx64",
    "kernel",
    "libs/acpi",
    "libs/apic",
    "libs/boot_info",
    "libs/debug",
    "libs/frame_allocator",
    "libs/pic",
    "libs/predefined_mmap",
    "libs/qemu",
    "libs/r_acpi",
    "libs/uefi",
    "libs/vm",
    "servers/init",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[patch.crates-io]
x86_64 = { git = "https://github.com/toku-sa-n/x86_64", branch = "flush_new" }
