[package]
name = "vm_server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "vm_server"
test = false

[lib]
test = false

[features]
test_on_qemu = []

[dependencies]
ipc = { path = "../../libs/ipc" }
rlibc = "1.0.0"
