[package]
name = "test_user_app"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "test_user_app"
test = false

[lib]
test = false

[features]
test_on_qemu = []

[dependencies]
rlibc = "1.0.0"
syscalls = { path = "../../libs/syscalls" }
