[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "link-args=/entry:efi_main /subsystem:efi_application",
    "-C", "prefer-dynamic=n",
    "-C", "no-redzone=y",
    "-C", "linker=lld-link",
]
