use core::{
    alloc::Layout,
    fmt,
    ops::{Deref, DerefMut},
    ptr::NonNull,
};

pub struct Kbox<T>(NonNull<T>);
impl<T> Kbox<T> {
    pub fn new(x: T) -> Self {
        let p: *mut T = super::alloc(Layout::new::<T>()).cast();
        let p = NonNull::new(p).expect("Failed to allocate memory.");

        // SAFETY: The pointer points to the allocated memory.
        unsafe {
            p.as_ptr().write(x);
        }

        Self(p)
    }
}
impl<T> Deref for Kbox<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        // SAFETY: The pointer points to the allocated, and initialized value.
        unsafe { self.0.as_ref() }
    }
}
impl<T> DerefMut for Kbox<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        // SAFETY: The pointer points to the allocated, and initialized value.
        unsafe { self.0.as_mut() }
    }
}
impl<T: fmt::Debug> fmt::Debug for Kbox<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&**self, f)
    }
}
impl<T> Drop for Kbox<T> {
    fn drop(&mut self) {
        // SAFETY: The pointer is generated by `alloc`, and the layout is the same as the one used
        // to allocate the memory.
        unsafe {
            super::dealloc(self.0.as_ptr().cast(), Layout::new::<T>());
        }
    }
}
