name: CI

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run rustfmt
        run: checkers/run_rustfmt.sh

  clippy:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings -D absolute_paths_not_starting_with_crate -D disjoint_capture_drop_reorder -D elided_lifetimes_in_paths -D explicit_outlives_requirements -D macro_use_extern_crate -D meta_variable_misuse -D missing_abi -D missing_copy_implementations -D missing_debug_implementations -D non_ascii_idents -D pointer_structural_match -D semicolon_in_expressions_from_macros -D single_use_lifetimes -D trivial_casts -D trivial_numeric_casts -D unaligned_references -D unreachable_pub -D unused_extern_crates -D unused_import_braces -D unused_lifetimes -D unused_qualifications

    steps:
      - uses: actions/checkout@v2

      - name: Install Clippy
        run: rustup component add clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D clippy::pedantic -D clippy::all

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install the Rust toolchain for Windows to build an UEFI binary
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install the other dependencies
        run: sudo apt-get install gcc-mingw-w64 lld mtools

      - name: Check if `lld-link` is installed
        run: which lld-link

      - name: Build the OS
        run: make -j$(nproc)
