name: CI

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run rustfmt
        run: checkers/run_rustfmt.sh

  clippy:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -D warnings

    steps:
      - uses: actions/checkout@v2

      - name: Install Clippy
        run: rustup component add clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D clippy::pedantic -D clippy::all

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install the Rust toolchain for Windows to build an UEFI binary
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install the other dependencies
        run: sudo apt-get install gcc-mingw-w64 mtools

      - name: Build the OS
        run: make -j$(nproc)
